### ISSUE TITLE
Thanks for sharing, Would it run on Colab?

### ISSUE THREAD

**Issue by amrrs** [rese1f/StableVideo#1]
I've not tried it yet but jut would love to hear if it runs on Free Colab (T4 - 16GB VRAM)

**Comment by rese1f** [comment]
please see the updated README.md @amrrs  :)

|   |VRAM (MiB)|
|---|---|
|float32|29145|
|amp|23005|
|amp + cpu|17639|
|amp + cpu + xformers|14185|

- cpu: use cpu cache as ControlNet, args: `save_memory`

under default setting (*e.g.* resolution, *etc.*) in `app.py`

**Comment by amrrs** [comment]
Thank you @rese1f Let me try if I can manage to run this on Colab :)

**Comment by amrrs** [comment]
Sorry for reopening, I was trying to replicate this on a colab. I didn't understand what all changes to be made on the app.py for this configuration

```
amp + cpu + xformers
```

Do you have any suggestion?

**Comment by rese1f** [comment]
@amrrs I guess there is someone create a colab demo in the "pull request", but I haven't check that. (cause I've never use colab before

**Comment by rese1f** [comment]
> Sorry for reopening, I was trying to replicate this on a colab. I didn't understand what all changes to be made on the app.py for this configuration
> 
> ```
> amp + cpu + xformers
> ```
> 
> Do you have any suggestion?

and for this one, I have set this optimization as default. The only thing that need to do is to addtional install xformers by `pip install xformers`.

**Comment by amrrs** [comment]
I had installed the xformers. I'll check the PR.
