### ISSUE TITLE
Does every video need to be trained before editing?

### ISSUE THREAD

**Issue by coollofty** [rese1f/StableVideo#10]
Use a 15s 1080p video as a benchmark and a 3090 24G graphics card to train the video model about how long (amp+cpu version)?

**Comment by rese1f** [comment]
You can train on your own video following [NLA](https://github.com/ykasten/layered-neural-atlases)

**Comment by coollofty** [comment]
Because my current graphics card cannot working, but I like this project very much, so I want to know a general situation, if this time is acceptable to me, then I plan to upgrade my graphics card. Can you give me a rough estimate? Thanks very much!

**Comment by rese1f** [comment]
I am glad you like this project. Here is a approximated cost
```
Training and evaluation requires ∼5GB GPU memory with videos consisting of 70 frames with resolution 768 × 432 and the checkpoint size is 14.3MB. Training our model takes about 10 hours per video, and reconstructing every video takes roughly 7 minutes on an NVIDIA Quadro RTX 6000 GPU.
```

**Comment by coollofty** [comment]
Okay, got it. Thank you
