### ISSUE TITLE
The background is always black

### ISSUE THREAD

**Issue by qxzha** [rese1f/StableVideo#16]
@rese1f , Thanks for your nice work!
But I met a hating problem.
I have trained my own video using the method of [NLA](https://github.com/ykasten/layered-neural-atlases), but when I made video style transfer using this work, the background of foreground is always black, which results in the render video's background is also 
 black. 
What could I do to get a surprising performance like your given demo video?

The bad vidoes are blow:

<img width="1272" alt="image" src="https://github.com/rese1f/StableVideo/assets/125275755/bbb2329b-a5c1-43be-a470-d2c2d0fbaf65">

**Comment by xiaoquan-serien** [comment]
<img width="1295" alt="image" src="https://github.com/rese1f/StableVideo/assets/125275755/8ab9f6c9-6700-48aa-a1ed-589dea718bb3">

**Comment by wenhaochai** [comment]
It seems not a bug but causing by the poor performance by Atlas, is the camera moving very fast?

**Comment by qxzha** [comment]
Yes, this camera moves very fast. And the figure has a big motion

Wenhao Chai ***@***.***> 于2023年11月10日周五 12:51写道：

**Comment by wenhaochai** [comment]
yea, that’s our limitation, u can try some video with less camera motion or cut the video into shorter clips to avoid this kind of failure case

**Comment by qxzha** [comment]
Thanks your fast reply, I will try some other videos.

Wenhao Chai ***@***.***> 于2023年11月12日周日 23:53写道：
